package com.mygdx.game.enums;

public enum CommandEnum {
    REMOVE_ENTITY_BY_ID,
    REMOVE_LAST_ENTITY,
    TOGGLE_ENTITY_DEBUG_BOX,
    ADD_ENTITY_AT_PLAYER_POSITION,
    LOAD_LEVEL_1,
    GENERATE_RANDOM_TILES,
    PRINT_EVENT_STATS,
    CLEAR_EVENT_LOG,
    TOGGLE_EVENT_LOGGING
}
