package com.mygdx.game.enums;

public enum RogueTypeEnum {
    DWARF,
    ELF,
    RANGER ,
    ROGUE,
    BANDIT,
    MALE_KNIGHT,
    MALE_FIGHTER ,
    FEMALE_KNIGHT,
    FEMALE_KNIGHT_HELMETLESS ,
    SHIELD_KNIGHT,
    MONK ,
    PRIEST ,
    FEMALE_WAR_CLERIC,
    MALE_WAR_CLERIC,
    TEMPLAR,
    MALE_BARBARIAN ,
    MALE_WINTER_BARBARIAN,
    FEMALE_WINTER_BARBARIAN,
    SWORDSMAN,
    FEMALE_WIZARD,
    MALE_WIZARD,
    DRUID,
    DESERT_SAGE
}
